# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test with jest

on: pull_request

env:
  SECRET_KEY: T3STS3CR3T
  MIGRATIONS_DIR: ci_migrations
  MONGODB_URI: ${{secrets.MONGODB_URI}}
  NODE_ENV: ci

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn pretest-ci && yarn test-ci
